#!/bin/sh

# Go to the directory
cd /mnt/c/Users/sadir/Documents/Github_Projects_2/Lab2-SigGen/task1

# Cleanup
rm -rf obj_dir
rm -f sinegen.vcd

# Run Verilator to translate Verilog into C++, including C++ testbench
# We must list ALL .sv files used in the design
verilator -Wall --cc --trace sinegen.sv counter.sv rom.sv --exe sinegen_tb.cpp

# Build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vsinegen.mk Vsinegen

# Run executable simulation file
obj_dir/Vsinegen