// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vdual_sinegen.cpp"
#include "Vdual_sinegen___024root__DepSet_hc01091e4__0.cpp"
#include "Vdual_sinegen__Trace__0.cpp"
#include "Vdual_sinegen___024root__Slow.cpp"
#include "Vdual_sinegen___024root__DepSet_hc01091e4__0__Slow.cpp"
#include "Vdual_sinegen__Syms.cpp"
#include "Vdual_sinegen__Trace__0__Slow.cpp"
